### ISSUE TITLE
Learn IDE

### ISSUE THREAD

**Issue by NYHolzer** [learn-co-curriculum/ruby-objects-has-many-through-lab#32]
I don't know if its local to this lab or has a wider scope. But my Learn IDE in browser is refreshing itself. Getting frozen every 2 minutes. It's really hard to go through the lab this way.

**Comment by maxwellbenton** [comment]
Hi @NYHolzer,

Thank you for providing this feedback. This bug was known and resolved in the Spring and should no longer be occuring with the new version of the in-browser Learn IDE, so this issue should now be resolved.

We apologize for any frustration you might have encountered.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
