### ISSUE TITLE
Question about the flow of this lab.

### ISSUE THREAD

**Issue by fbohz** [learn-co-curriculum/ruby-objects-has-many-through-lab#35]
Hello there! 

I was working on it through learn --f-f. The flow of this lab is asking songs method before writing it.  Here's the new_song method (just before song method)
```ruby
  describe "#new_song" do
    it "given a name and genre, creates a new song associated with that artist" do
      jay_z = Artist.new("Jay-Z")
      rap = Genre.new("rap")
      ninety_nine_problems = jay_z.new_song("Ninety Nine Problems", rap)

     #here jay_z.songs
      expect(jay_z.songs).to include(ninety_nine_problems)
      expect(ninety_nine_problems.artist).to eq(jay_z)
    end
  end
```
Shouldn't the songs method be actually before the new_song?

**Comment by fbohz** [comment]
Also by the way the tests I was able to pass the appointments method by just a simple .each method not testing for equality:
```ruby 
def appointments
    Appointment.all.each { |appointment| appointment.doctor }
  end 
```

**Comment by maxwellbenton** [comment]
Hi @fbohz,

Thank you for providing this feedback. We've updated the tests in this lesson and incorporated fixes based on this information. `new_song` (as well as `new_appointment`) has been updated so that it `songs` is tested first before it is used in the `new_song` tests.  We've also updated the tests for `appointments` and `songs` so that they are checking for the appropriate relationships instead of what is being returned.

We apologize for any inconvenience this may have caused you, but thank you for contributing to this lesson and ensuring future students will not encounter these issues.
