### ISSUE TITLE
Appointments are not being created according to 

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/ruby-objects-has-many-through-lab#37]
@maxwellbenton the recent changes you made to this lab are breaking. The arguments for the appointments being created in https://github.com/MrsAud/ruby-objects-has-many-through-lab-online-web-ft-071519/blob/b90caf9a729005bfd49618cd2ea56bd385866491/spec/06_patient_spec.rb#L37, for example, are in the wrong order. The same for the updates made in the doctor_spec. I will try to create a PR if I have time before my shift is over. Thanks!

**Comment by maxwellbenton** [comment]
Hey @kwebster2,

Thanks for letting me know about this. The new tests were written based of the existing solution, which was not aligned to the readme instructions. I've updated the tests and solution so that they align with the instructions and added in additional code snippet examples to help ensure the corrected order of parameters in `Appointment#initialize`.

Sorry for any confusion this may have caused! This should now be resolved
